## Configuration for the training, evaluation
samples:
  - name: Z2tau2pinu
    label: 1
    path: ../data/Z2pinu_images/*.h5
    xsec: 1
    ngen: 1
  - name: Z2tau2pipipinu
    label: 0
    path: ../data/Z2pipipinu_images/*.h5
    xsec: 1
    ngen: 1
  - name: Z2tau2pipipipizeronu
    label: 2
    path: ../data/Z2pipipipizero_images/*.h5
    xsec: 1
    ngen: 1
  - name: Z2tau2pipizeronu
    label: 3
    path: ../data/Z2pipizeronu_images/*.h5
    xsec: 1
    ngen: 1
  - name: Z2tau2pipizeropizeronu
    label: 4
    path: ../data/Z2pipizeropizeronu_images/*.h5
    xsec: 1
    ngen: 1
  - name: Z2tau2qqbar
    label: 5
    path: ../data/Z2qqbar_images/*.h5
    xsec: 1
    ngen: 1
training:
    randomSeed1: 123456
    nDataLoaders: 4

